export enum SALE_STATE {
  'FIRST_CONTACT' = 'FIRST_CONTACT',
  'PROPOSAL' = 'PROPOSAL',
  'REVIVAL' = 'REVIVAL',
  'NEGOTIATION' = 'NEGOTIATION',
  'REFUSAL' = 'REFUSAL',
  'ABANDONMENT' = 'ABANDONMENT',
  'WON' = 'WON',
}

export enum SALE_SOURCE {
  'CANVASSING' = 'CANVASSING',
  'INCOMING_CALL' = 'INCOMING_CALL',
  'WORD_OF_MOUTH' = 'WORD_OF_MOUTH',
  'NETWORK' = 'NETWORK',
  'LOUNGE' = 'LOUNGE'
}

export enum SALE_ACTION_STATE {
  'TODO' = 'TODO',
  'IN_PROGRESS' = 'IN_PROGRESS',
  'ON_BREAK' = 'ON_BREAK',
  'FINISH' = 'FINISH',
  'STOP' = 'STOP'
}
