# Generated by Django 2.2.6 on 2019-11-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_firstname', models.CharField(max_length=255)),
                ('contact_lastname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_update', models.DateTimeField(blank=True, default=None, null=True)),
                ('dt_created', models.DateTimeField(blank=True, default=None, null=True)),
                ('amount_signed', models.FloatField(blank=True, default=None, null=True)),
                ('dt_next_action', models.DateField(blank=True, default=None, null=True)),
                ('comment', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('sale_state', models.CharField(blank=True, choices=[('FIRST_CONTACT', 'FIRST_CONTACT'), ('PROPOSAL', 'PROPOSAL'), ('REVIVAL', 'REVIVAL'), ('NEGOTIATION', 'NEGOTIATION'), ('REFUSAL', 'REFUSAL'), ('ABANDONMENT', 'ABANDONMENT'), ('WON', 'WON')], default=None, max_length=35, null=True)),
                ('sale_source', models.CharField(blank=True, choices=[('CANVASSING', 'CANVASSING'), ('INCOMING_CALL', 'INCOMING_CALL'), ('WORD_OF_MOUTH', 'WORD_OF_MOUTH'), ('NETWORK', 'NETWORK'), ('LOUNGE', 'LOUNGE')], default=None, max_length=35, null=True)),
                ('sale_action_state', models.CharField(blank=True, choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ON_BREAK', 'ON_BREAK'), ('FINISH', 'FINISH'), ('STOP', 'STOP')], default=None, max_length=35, null=True)),
                ('attachment', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='crm_editor.School')),
            ],
        ),
    ]
