# Generated by Django 2.2.6 on 2019-10-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dt_created', models.DateField()),
                ('dt_update', models.DateField()),
                ('dt_next_action', models.DateField()),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
    ]
