# Generated by Django 2.2.6 on 2019-10-15 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contact_firstname', models.CharField(max_length=255)),
                ('contact_lastname', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='amount_signed',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_action_state',
            field=models.CharField(blank=True, choices=[('TODO', 'TODO'), ('IN_PROGRESS', 'IN_PROGRESS'), ('ON_BREAK', 'ON_BREAK'), ('FINISH', 'FINISH'), ('STOP', 'STOP')], default=None, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_source',
            field=models.CharField(blank=True, choices=[('CANVASSING', 'CANVASSING'), ('INCOMING_CALL', 'INCOMING_CALL'), ('WORD_OF_MOUTH', 'WORD_OF_MOUTH'), ('NETWORK', 'NETWORK'), ('LOUNGE', 'LOUNGE')], default=None, max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_state',
            field=models.CharField(blank=True, choices=[('FIRST_CONTACT', 'FIRST_CONTACT'), ('PROPOSAL', 'PROPOSAL'), ('REVIVAL', 'REVIVAL'), ('NEGOTIATION', 'NEGOTIATION'), ('REFUSAL', 'REFUSAL'), ('ABANDONMENT', 'ABANDONMENT'), ('WON', 'WON')], default=None, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='dt_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='dt_next_action',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='dt_update',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='sale',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_editor.School'),
        ),
    ]
