# Generated by Django 2.2.6 on 2019-10-15 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_editor', '0002_auto_20191015_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='school',
        ),
    ]
