# Generated by Django 2.2.6 on 2019-10-15 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_editor', '0003_remove_sale_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_editor.School'),
        ),
    ]
