# Generated by Django 2.2.6 on 2019-10-17 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_editor', '0005_auto_20191016_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='crm_editor.School'),
        ),
    ]
